name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest' ] # 'windows-latest' too flaky
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test (headless with xvfb in Linux)
        run: xvfb-run mvn clean verify -PuseJenkinsSnapshots
        if: matrix.os == 'ubuntu-latest'
        working-directory: org.eclipse.xtext.p2.releng

      - name: Build and test (in other OSes)
        run: mvn clean verify -PuseJenkinsSnapshots
        if: matrix.os != 'ubuntu-latest'
        working-directory: org.eclipse.xtext.p2.releng

  build-maven-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            !**/*xtext*
            !**/*xtend*
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build Maven artifacts
        run: ./maven-build.sh